server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/yeom-enong/IdeaProjects/localRepo
        git: # git? default??.
#          uri: file:///Users/yeom-enong/IdeaProjects/localRepo #window??? file://C:\\Users\\yeom-enong\\IdeaProjects\\localRepo
          uri: https://github.com/hykqo/study-spring-cloud-config.git
#          username: [ID] 퍼블릭 레파지토리이기 때문에 사용 X
#          password: [PASSWORD]
          default-label : main

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, httptrace